### ISSUE TITLE
Step does not pick the right provisioning profiles

### ISSUE THREAD

**Issue by wqz-leo** [bitrise-steplib/steps-xcode-build-for-test#4]
The scheme which specified in the step is `QA2`, so it should use `co.massive.axis.qa2` profile in theory.
However, this step is picking up `co.massive.axis.demo` instead.

[98f884723d085774.log](https://github.com/bitrise-steplib/steps-xcode-build-for-test/files/2537229/98f884723d085774.log)

**Comment by wangqingzhouleo** [comment]
I also tried to change the scheme to `Demo`, but it's still throwing the same error.
This step is added after `Certificate and profile installer` as per [this](https://devcenter.bitrise.io/testing/device-testing-for-ios/) instruction.

**Comment by MattCheetham** [comment]
Seems like you're having similar issues to me: https://discuss.bitrise.io/t/xcode-ui-test-build-for-testing-fails/6718

**Comment by fehersanyi-bitrise** [comment]
Hy there!
@wangqingzhouleo please try inserting `-UseModernBuildSystem=NO` in the steps debug field's `Addicional Options for Xcodebuild call` input.

**Comment by pahnev** [comment]
Thanks @fehersanyi-bitrise. I got progress with that flag, but now I'm getting this error:
`Error Domain=NSCocoaErrorDomain Code=4 "The folder “TestDemo_iphoneos12.0-arm64e.xctestrun” doesn’t exist."`

**Comment by fehersanyi-bitrise** [comment]
@pahnev well, could you try running a tree command before that step, to check where the .xctestrun actually is?

**Comment by charleshberlin** [comment]
I have a similar issue that gives an error about my UI tests

❌  error: There are no accounts registered with Xcode. Add your developer account to Xcode (in target '****-UITests')
❌  error: No profiles for 'com.****-UITests' were found: Xcode couldn't find any iOS App Development provisioning profiles matching '****-UITests'. (in target '****-UITests')

**Comment by ahvth-bitrise** [comment]
Just wanted to note that @charleshberlin 's issue was solved by disabling "Automatically manage signing" in the UITests target in Xcode.

![image](https://user-images.githubusercontent.com/51318679/62040394-d92ba500-b1f9-11e9-95bc-cbe2b86f9b67.png)

**Comment by dimple-doshi** [comment]
How was this resolved? I'm still facing this error `Xcode couldn't find any provisioning profiles matching ''`
I tried the above mentioned solutions.

**Comment by qbnce** [comment]
Hi @dimple-doshi! The messaging itself can have a number of causes, the most common culprit is the setting above your comment. If you'd like us to take a look at your issue, please paste an URL for a build here!

**Comment by bitce** [comment]
Hi @dimple-doshi! The messaging itself can have a number of causes, the most common culprit is the setting above your comment. If you'd like us to take a look at your issue, please paste an URL for a build here!
