### ISSUE TITLE
Step failing to create the `testbundle.zip`

### ISSUE THREAD

**Issue by empowerCassie** [bitrise-steplib/steps-xcode-build-for-test#42]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.0.0
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? SPORADIC
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO

### Useful information

- Using the following two steps which rely on each other
    - [Xcode build for test](https://github.com/bitrise-steplib/steps-xcode-build-for-test)
    - [Virtual Device Testing for iOS](https://github.com/bitrise-steplib/steps-virtual-device-testing-for-ios)

### Issue description

On occasion the Xcode build for the test step fails to create the ZIP file, the step still passes but then the Virtual Device Testing step will fail because it doesn't have the ZIP it needs.

Given this is sporadic we have been rebuilding the same commits. Can't find a rhyme or reason to the failure.

### Bitrise info

- Build URL: https://app.bitrise.io/build/37537d32-2919-4201-b635-85b769ed15e7
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES

<details>
  <summary>Log</summary>
  <pre>
zip "-r" "/Users/[REDACTED]/deploy/testbundle.zip" "Dev-iphoneos" "[REDACTED]_iphoneos15.4-arm64.xctestrun" failed: adding: Dev-iphoneos/ (stored 0%)

adding: X [redacted there are lots of these]

adding: Dev-iphoneos/arm64-[REDACTED].csym
zip warning: No such file or directory
    zip warning: could not open for reading: Dev-iphoneos/arm64-[REDACTED].csym

adding: X [redacted there are lots of these]

zip warning: Not all files were readable
    files/entries read:  1509 (707M bytes)  skipped:  1 (22M bytes)
  </pre>
</details>

### Steps to reproduce
Not sure of specific steps since it happens sporadically even on the same commit.

**Comment by tzuhan-bitrise** [comment]
Hi Cassie, thank you for contacting Bitrise.
I'm Tzuhan from the Bitrise technical specialist team.
Would you mind submitting a ticket through [Bitrise Support](thttps://support.bitrise.io/hc/en-us)? 
Please include the Build URL and enable the support access.
Thank you.
