### ISSUE TITLE
Step is unable to export .xctestrun after test build succeeds

### ISSUE THREAD

**Issue by anuragajwani** [bitrise-steplib/steps-xcode-build-for-test#5]
Hi,

I am encountering an error when running version `0.2.0` of this step on Bitrise. Once the build for test succeeds the steps tries to export the file using the incorrect file name.

i.e.
Workspace path: MyWorkspace.xcworkspace
SchemeName: SuperApp
ConfigurationName: Debug
Device destination: generic/platform=iOS

Once the test build succeeds it fails to export:
`No xctestrun file found with pattern: /Users/vagrant/Library/Developer/Xcode/DerivedData/MyWorksapce-eiwzeuzkbmcrucabwlesgwmjrypa/Build/Products/MyWorkspace*.xctestrun, error: %!s(<nil>)`

Please help,
Anurag

**Comment by anuragajwani** [comment]
Found the line that assumes the xctestrun file generated is based on the project name https://github.com/bitrise-steplib/steps-xcode-build-for-test/blob/master/main.go#L220

`xctestrunPthPattern := filepath.Join(symRoot, fmt.Sprintf("%s*.xctestrun", projectName))`

Not sure what the ideal solution would be here, for now maybe include in search something like
`xctestrunPthPatternScheme := filepath.Join(symRoot, fmt.Sprintf("%s*.xctestrun", **schemeName**))`?

**Comment by bitce** [comment]
Hi @anuragajwani 

Sorry to hear about these issues, could you please include a build URL as well?

**Comment by bartzet** [comment]
Hey,
Here you go:
https://app.bitrise.io/build/17fdbdcfb9f94e2e

**Comment by lpusok** [comment]
Hi,
There is a new release in progress, that fixes the issue:
<https://discuss.bitrise.io/t/beta-xcode-build-for-testing-for-ios-v0-2-1/6854>

**Comment by lpusok** [comment]
Hi,
The new version is now available. Thanks for the report all, the issue is closed for now. Please report any problem you encounter, and will reopen.
